### ISSUE TITLE
s@ doesn't work

### ISSUE THREAD

**Issue by chocolateboy** [ivanwills/node-getopt-long#3]
(Thanks for this module. I miss the sanity and flexibility of Perl's Getopt::Long in Nodeland, and this is the best replacement I've found so far.)

`s@` doesn't appear to work: it produces the same result as `s`:

### Test

```javascript
var Assert = require('assert');
var Getopt = require('node-getopt-long');

process.argv.splice(2, process.argv.length - 2, '--array', 'foo', '-a', 'bar');

var options = Getopt.options([
    [ 'array|a=s@', 'slurp strings into an array' ]
]);

Assert.deepEqual(options, { array: [ 'foo', 'bar' ] });
```

### Output:

```
AssertionError: { array: 'bar' } deepEqual { array: [ 'foo', 'bar' ] }
```

**Comment by ivanwills** [comment]
Sorry for taking time to fix, but the fix is now in v0.3.0
