### ISSUE TITLE
--version doesn't print the version

### ISSUE THREAD

**Issue by chocolateboy** [ivanwills/node-getopt-long#5]
node-getopt-long: 0.3.0
node: v4.1.0
OS: Linux (Arch)

If `commandVersion` is set and the command is called with `--version`, I would expect the command to print the version and exit, as it says in the help message:

> --version  Show the version of this command

However, it doesn't appear to be implemented:

    $ cat ./command.js

```javascript
var Getopt = require('node-getopt-long');

var options = Getopt.options(
    [
        [ 'foo|f=s', 'foo the bar' ],
    ],
    {
        commandVersion: '0.0.1',
        name: 'command',
    }
);

console.log("Shouldn't get here");
```

```
$ node ./command.js --version
```
 
    Shouldn't get here

**Comment by ivanwills** [comment]
Fixed in v0.3.1
